In [1]:
import torch

In [2]:
scalar1 = torch.tensor([1.])

In [4]:
scalar2 = torch.tensor([3.])

In [5]:
add_scalar = scalar1 + scalar2

In [6]:
add_scalar

tensor([4.])

In [7]:
sub_scalar = scalar1 - scalar2

In [8]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [12]:
vector1 = torch.tensor([1., 2., 3.])

In [13]:
vector1

tensor([1., 2., 3.])

In [14]:
matrix1 = torch.tensor([[1.,2.],[3.,4.]])

In [15]:
matrix1

tensor([[1., 2.],
        [3., 4.]])

In [16]:
# torch autograd 
# autograd란 자동미분엔진

In [18]:
import torch

if torch.cuda.is_available():
  DEVICE = torch.device('cuda')
else:
  DEVICE = torch.device('cpu')

In [19]:
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10 

''' BATCH SIZE는, 딥러닝 모델에서 파라미터를 업데이트 할 때 계산되는 데이터의 개수
BATCH SIZE수만큼 데이터를 이용해 output을 계산하고 출력된 결괏값에 대한 오차를 계산, 64 -> input으로 이용되는 데이터가 64개 의미
input size는 입력층의 노드 수를 의미, 입력데이터의 크기가 1000이라는 것을 의미, 1000크기의 벡터값 배치가64이므로 1000크기의 벡터를 64개 이용한다는 의미 = (64,1000)
Hidden size는 딥러닝 모델에서 Input을 다수의 파라미터를 이용해 계산한 결과에 한 번 더 계산되는 파라미터 수를의미한다. 입력->은닉층으로 전달 됐을때 은닉층의 노드 수를 의미
이 예제에서는 (64, 1000) Input들이 (1000, 100) 크기의 행렬과 행렬곱을계산함 '''

' BATCH SIZE는, 딥러닝 모델에서 파라미터를 업데이트 할 때 계산되는 데이터의 개수\nBATCH SIZE수만큼 데이터를 이용해 output을 계산하고 출력된 결괏값에 대한 오차를 계산, 64 -> input으로 이용되는 데이터가 64개 의미\ninput size는 입력층의 노드 수를 의미, 입력데이터의 크기가 1000이라는 것을 의미, 1000크기의 벡터값 배치가64이므로 1000크기의 벡터를 64개 이용한다는 의미 = (64,1000)\nHidden size는 딥러닝 모델에서 Input을 다수의 파라미터를 이용해 계산한 결과에 한 번 더 계산되는 파라미터 수를의미한다. 입력->은닉층으로 전달 됐을때 은닉층의 노드 수를 의미\n이 예제에서는 (64, 1000) Input들이 (1000, 100) 크기의 행렬과 행렬곱을계산함 '

In [20]:
# torch.randn - 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 텐서 생성

x = torch.randn(BATCH_SIZE,
                INPUT_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = False)
y = torch.randn(BATCH_SIZE,
                OUTPUT_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = False)
w1 = torch.randn(INPUT_SIZE,
                 HIDDEN_SIZE,
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True) # 역전파를통한 업데이트해야되는 대상이면 True 
w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE,
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)



In [37]:
learning_rate = 1e-6 # learning_rate란, 어느정도 크기로 기울기가 줄어드는 지점까지 이동하겠는가 
for t in range(1, 501):
  y_pred = x.mm(w1).clamp(min=0).mm(w2) # mm은 matrix mul , 여기서 clamp는 relu와 같은 역할을 함 

  loss = (y_pred - y).pow(2).sum()
  if t % 100 == 0:
    print("iteration: ", t, "\t", "Loss: ", loss.item())
  loss.backward() # 각 파라미터 값에 대해 Gradient를 계산하고 Back Propagation진행한다는 것을 의미 

  with torch.no_grad(): # Gradient를 고정한다는 의미 
    w1 -= learning_rate * w1.grad 
    w2 -= learning_rate * w2.grad

    w1.grad.zero_() # 파라미터를 업데이트 했다면, gradient를 0으로 초기화해 다음 반복문 진행할수있도록 함. 
    w2.grad.zero_()

iteration:  100 	 Loss:  nan
iteration:  200 	 Loss:  nan
iteration:  300 	 Loss:  nan
iteration:  400 	 Loss:  nan
iteration:  500 	 Loss:  nan
